// macro_rules! material_colors {
//     ($($name: ident, $id: literal => $color: literal),* ) => {
//         #[allow(non_camel_case_types)]
//         pub enum MaterialColor {
//             $($name), *
//         }

//         impl MaterialColor {
//             pub fn get_value(&self) -> u32 {
//                 match self {
//                     $(Self::$name => $color), *
//                 }
//             }
//             pub fn from_id(id: u32) -> Option<MaterialColor> {
//                 match id {
//                     $($id => Some(MaterialColor::$name)),*,
//                     _ => None
//                 }
//             }
//             pub fn to_id(&self) -> u32 {
//                 match self {
//                     $(MaterialColor::$name => $id),*
//                 }
//             }
//         }
//     }
// }

// macro_rules! materials {
//     ($($name: ident => $material: expr),* ) => {
//         $(const $name: &Material = &$material);*;

//         #[allow(non_camel_case_types)]
//         pub enum Materials {
//             $($name), *
//         }
//         impl Materials {
//             pub fn get(&self) -> &Material {
//                 match self {
//                     $(Self::$name => $name), *
//                 }
//             }
//         }
//     }
// }

// pub enum PushReaction {
//     Normal,
//     Destroy,
//     Block,
//     Ignore,
//     PushOnly,
// }

// material_colors!(
//     NONE, 0 => 0,
//     GRASS, 1 => 8368696,
//     SAND, 2 => 16247203,
//     WOOL, 3 => 13092807,
//     FIRE, 4 => 16711680,
//     ICE, 5 => 10526975,
//     METAL, 6 => 10987431,
//     PLANT, 7 => 31744,
//     SNOW, 8 => 16777215,
//     CLAY, 9 => 10791096,
//     DIRT, 10 => 9923917,
//     STONE, 11 => 7368816,
//     WATER, 12 => 4210943,
//     WOOD, 13 => 9402184,
//     QUARTZ, 14 => 16776437,
//     COLOR_ORANGE, 15 => 14188339,
//     COLOR_MAGENTA, 16 => 11685080,
//     COLOR_LIGHT_BLUE, 17 => 6724056,
//     COLOR_YELLOW, 18 => 15066419,
//     COLOR_LIGHT_GREEN, 19 => 8375321,
//     COLOR_PINK, 20 => 15892389,
//     COLOR_GRAY, 21 => 5000268,
//     COLOR_LIGHT_GRAY, 22 => 10066329,
//     COLOR_CYAN, 23 => 5013401,
//     COLOR_PURPLE, 24 => 8339378,
//     COLOR_BLUE, 25 => 3361970,
//     COLOR_BROWN, 26 => 6704179,
//     COLOR_GREEN, 27 => 6717235,
//     COLOR_RED, 28 => 10040115,
//     COLOR_BLACK, 29 => 1644825,
//     GOLD, 30 => 16445005,
//     DIAMOND, 31 => 6085589,
//     LAPIS, 32 => 4882687,
//     EMERALD, 33 => 55610,
//     PODZOL, 34 => 8476209,
//     NETHER, 35 => 7340544,
//     TERRACOTTA_WHITE, 36 => 13742497,
//     TERRACOTTA_ORANGE, 37 => 10441252,
//     TERRACOTTA_MAGENTA, 38 => 9787244,
//     TERRACOTTA_LIGHT_BLUE, 39 => 7367818,
//     TERRACOTTA_YELLOW, 40 => 12223780,
//     TERRACOTTA_LIGHT_GREEN, 41 => 6780213,
//     TERRACOTTA_PINK, 42 => 10505550,
//     TERRACOTTA_GRAY, 43 => 3746083,
//     TERRACOTTA_LIGHT_GRAY, 44 => 8874850,
//     TERRACOTTA_CYAN, 45 => 5725276,
//     TERRACOTTA_PURPLE, 46 => 8014168,
//     TERRACOTTA_BLUE, 47 => 4996700,
//     TERRACOTTA_BROWN, 48 => 4993571,
//     TERRACOTTA_GREEN, 49 => 5001770,
//     TERRACOTTA_RED, 50 => 9321518,
//     TERRACOTTA_BLACK, 51 => 2430480,
//     CRIMSON_NYLIUM, 52 => 12398641,
//     CRIMSON_STEM, 53 => 9715553,
//     CRIMSON_HYPHAE, 54 => 6035741,
//     WARPED_NYLIUM, 55 => 1474182,
//     WARPED_STEM, 56 => 3837580,
//     WARPED_HYPHAE, 57 => 5647422,
//     WARPED_WART_BLOCK, 58 => 1356933,
//     DEEPSLATE, 59 => 6579300,
//     RAW_IRON, 60 => 14200723,
//     GLOW_LICHEN, 61 => 8365974
// );

// pub struct Material {
//     pub color: MaterialColor,
//     pub liquid: bool,
//     pub solid: bool,
//     pub blocks_motion: bool,
//     pub solid_blocking: bool,
//     pub flammable: bool,
//     pub replaceable: bool,
//     pub push_reaction: PushReaction,
// }

// materials!(
//     AIR => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Normal,
//     },
//     STRUCTURAL_AIR => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Normal,
//     },
//     PORTAL => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Block,
//     },
//     CLOTH_DECORATION => Material {
//         color: MaterialColor::WOOL,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     PLANT => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     WATER_PLANT => Material {
//         color: MaterialColor::WATER,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     REPLACEABLE_PLANT => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: true,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     REPLACEABLE_FIREPROOF_PLANT => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     REPLACEABLE_WATER_PLANT => Material {
//         color: MaterialColor::WATER,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     WATER => Material {
//         color: MaterialColor::WATER,
//         liquid: true,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     BUBBLE_COLUMN => Material {
//         color: MaterialColor::WATER,
//         liquid: true,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     LAVA => Material {
//         color: MaterialColor::FIRE,
//         liquid: true,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     TOP_SNOW => Material {
//         color: MaterialColor::SNOW,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     FIRE => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: true,
//         push_reaction: PushReaction::Destroy,
//     },
//     DECORATION => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     WEB => Material {
//         color: MaterialColor::WOOL,
//         liquid: false,
//         solid: true,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     SCULK => Material {
//         color: MaterialColor::COLOR_BLACK,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     BUILDABLE_GLASS => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     CLAY => Material {
//         color: MaterialColor::CLAY,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     DIRT => Material {
//         color: MaterialColor::DIRT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     GRASS => Material {
//         color: MaterialColor::GRASS,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     ICE_SOLID => Material {
//         color: MaterialColor::ICE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     SAND => Material {
//         color: MaterialColor::SAND,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     SPONGE => Material {
//         color: MaterialColor::COLOR_YELLOW,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     SHULKER_SHELL => Material {
//         color: MaterialColor::COLOR_PURPLE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     WOOD => Material {
//         color: MaterialColor::WOOD,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     NETHER_WOOD => Material {
//         color: MaterialColor::WOOD,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     BAMBOO_SAPLING => Material {
//         color: MaterialColor::WOOD,
//         liquid: false,
//         solid: true,
//         blocks_motion: false,
//         solid_blocking: true,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     BAMBOO => Material {
//         color: MaterialColor::WOOD,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     WOOL => Material {
//         color: MaterialColor::WOOL,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     EXPLOSIVE => Material {
//         color: MaterialColor::FIRE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: false,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     LEAVES => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: false,
//         flammable: true,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     GLASS => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     ICE => Material {
//         color: MaterialColor::ICE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     CACTUS => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     STONE => Material {
//         color: MaterialColor::STONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     METAL => Material {
//         color: MaterialColor::METAL,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     SNOW => Material {
//         color: MaterialColor::SNOW,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     HEAVY_METAL => Material {
//         color: MaterialColor::METAL,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Block,
//     },
//     BARRIER => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Block,
//     },
//     PISTON => Material {
//         color: MaterialColor::STONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Block,
//     },
//     MOSS => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     VEGETABLE => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     EGG => Material {
//         color: MaterialColor::PLANT,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     CAKE => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     AMETHYST => Material {
//         color: MaterialColor::COLOR_PURPLE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     POWDER_SNOW => Material {
//         color: MaterialColor::SNOW,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     },
//     FROGSPAWN => Material {
//         color: MaterialColor::WATER,
//         liquid: false,
//         solid: false,
//         blocks_motion: false,
//         solid_blocking: false,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Destroy,
//     },
//     FROGLIGHT => Material {
//         color: MaterialColor::NONE,
//         liquid: false,
//         solid: true,
//         blocks_motion: true,
//         solid_blocking: true,
//         flammable: false,
//         replaceable: false,
//         push_reaction: PushReaction::Normal,
//     }
// );
