[package]
name = "minecrat-server-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version ="1.21.0", features = ["full"] }
openssl = "0.10.28"
rand = "0.8.5"
reqwest = "0.11.11"
aes = "0.8.1"
cfb8 = "0.8.1"